
GET http://localhost:3000/tracks

###

GET http://localhost:3000/tracks

###
POST http://localhost:3000/tracks/addField
###
GET http://localhost:3000/contestants

###
POST http://localhost:3000/contestants
Content-Type: application/json

{
    name: "First one"
    email: "something@mail.com"
}